name = input()
number = int(input())
# print(f"Группа №{number//100}.")
# print(f"{number%10}. {name}.")
# print(f"Шкафчик: {number}.")
# print(f"Кроватка: {number//10%10}.")

print("Группа  №" + str(number//100) + ".")
print(str(number%10) + "." + name + ".")
print("Шкафчик: " + str(number) + ".")
print("Кроватка: " + str(number//10%10) + ".")