name = input()
price = int(input())
weight = int(input())
money = int(input())

print('================Чек================')
print(f'Товар: {name:>28}')
print(f"Цена:{(str(weight) + 'кг * ' + str(price) + 'руб/кг'):>30}")
print(f"Итого: {str(price * weight) + 'руб':>28}")
print(f"Внесено: {str(money) + 'руб':>26}")
print(f"Сдача: {str(money - price * weight) + 'руб':>28}")
print('===================================')